# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup DocFx
        run: |
          nuget install docfx.console -Version 2.58.9
          mkdir D:\a\Flea\Flea\docfx.console.2.58.9\tools\Plugins
          nuget install rest.tagpage -OutputDirectory D:\a\Flea\Flea\docfx.console.2.58.9\tools\Plugins
      - name: Generate DocFx Data
        run: |
          D:\a\Flea\Flea\docfx.console.2.58.9\tools\docfx init -q
          mv ./Flea/* ./docfx_project/src
          mv ./api_spec.yaml ./docfx_project/src
          cd ./docfx_project
          D:\a\Flea\Flea\docfx.console.2.58.9\tools\docfx metadata
      - name: Add Articles
        run: |
          IF ( Test-Path -Path ./Articles/index.md -PathType Leaf) { `
             Remove-Item ./docfx_project/index.md `
             mv ./Articles/index.md ./docfx_project/ } `
          ELSE { `
             echo "Missing Home" }
          IF ( Test-Path -Path ./Articles/toc.yml -PathType Leaf) { `
             Remove-Item ./docfx_project/articles/* `
             mv ./Articles/* ./docfx_project/articles } `
          ELSE { `
             echo "Missing Toc" }
      - name: Generate Documentation
        run: |
          dir
          D:\a\Flea\Flea\docfx.console.2.58.9\tools\docfx docfx_project/docfx.json -t default,<output>/rest.tagpage.<version>/content
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: D:\a\Flea\Flea\docfx_project\_site
          destination_dir: DOC
